dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: pythondemocpe
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.3
- name: pythonwip
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.7
